### PR TITLE
Added Schedule Task Disable OIM User

### PR DESCRIPTION
**Pull request by MonikaMK**

### CODE REVIEW

**Comment by phi1ipp** [comment]
Monika, could you please check/change a constant for user status to be 
UserManagerConstants.AttributeValues.USER_STATUS_ACTIVE.getId()

**Comment by MonikaMK** [comment]
Modified and committed code as suggested.

**Comment by phi1ipp** [comment]
Sorry, Monika, could you please also change the class name to something more specific, like DisableUsersInOrgTask?

**Comment by MonikaMK** [comment]
I have updated class name. tested and committed it. Please verify at your end.

**Pull request merged**
